module.exports = {
  testEnvironment: "node",
  testMatch: ["<rootDir>/tests/**/*.test.js"],
  setupFilesAfterEnv: ["<rootDir>/tests/setup.js"],
  clearMocks: true,
  restoreMocks: true,
  collectCoverage: true,
  coverageProvider: "v8",
  coverageDirectory: "<rootDir>/coverage",
  collectCoverageFrom: [
    "src/controllers/authController.js",
    "src/controllers/categoryController.js",
    "src/controllers/deliveryController.js",
    "src/controllers/orderController.js",
    "src/controllers/productController.js",
    "src/middleware/authMiddleware.js",
    "src/middleware/errorMiddleware.js",
    "src/middleware/roleMiddleware.js",
    "src/middleware/sanitizeMiddleware.js",
    "src/routes/authRoutes.js",
    "src/routes/categoryRoutes.js",
    "src/routes/orderRoutes.js",
    "src/routes/productRoutes.js",
    "src/services/authService.js",
    "src/services/categoryService.js",
    "src/services/deliveryService.js",
    "src/services/orderService.js",
    "src/services/productService.js",
    "src/utils/jwt.js",
    "src/utils/roles.js",
  ],
};
